### PR TITLE
Add EnumerableSetDB for O(1) operation

### PR DESCRIPTION
**Pull request by sink772**

### CODE REVIEW

**Review by gedanziger — APPROVED** [review]
This looks great, @dbrehmer can also take a look.

I might have to make one accompanying change since a remove can mutate the ordering of the list, but that won't be related to this data structure.

**Comment by sink772** [comment]
Yes, this is `Set` data structure, naturally no guarantees are made on the ordering.  The `pop and swap` scheme is commonly used method to manipulate the array data items. If you want to keep the insertion ordering, you need to use the linked list structure.

**Comment by sink772** [comment]
As @gedanziger and I discussed internally,  the `remove` method is modified to return the swapped item value for later processing.

**Comment by gedanziger** [comment]
Added issue #180 to handle submitting the items that get re-ordered on remove. I think this PR is ready to go in, and a subsequent one will handle that.

**Review by dbrehmer — APPROVED** [review]
Looks good to me. I think this would be better than the linked list for where I am tracking nonzero borrower indexes in loans as well.

**Pull request merged**
