### PR TITLE
fee-conversion functionality

### PR DESCRIPTION
**Pull request by Skyvell**
**Changes overview**

Fee handler contract:
- Takes incomming fees, processes them and redirects them to their intended destination.

Dex contract:
- Redirect dex trading fees to fee handler contract.
- Users can now specify where the funds should end up when they are performing a swap.

Governance contract:
- Added fee handler address to the contract.
- Added a method which other contracts can call to get any address controlled by the governance contract.

Loans Contract:
- Redirect origination fees to fee handler contract.

Router contract:
- Users can now specify where the funds should end up when performing a swap.

### CODE REVIEW

**Review by dbrehmer — CHANGES_REQUESTED** [review]
Nice clean code. Nice to have the receiver parameter for trades.

Having the getContractAddress method is a good idea.

My only concern is about the cost of interscore calls required to always retrieve the addresses from governance and the use of the json_loads and json_dumps api calls. I think this may be okay, but the costs could add up. Router calls especially could make a lot of interscore calls. One interscore call costs 25000 step. That is 1/4 of the base transaction fee of 100000 step. json_loads is 40000 and json_dumps is 50000 plus I think there is some cost per byte of data.

I'm not sure what the limit will be on the number of router hops, but if someone makes a router call with 5 hops how many interscore calls and json_loads / json_dumps could that contain? I know the fee handler will only do one conversion per transaction, which is great, but I am still unclear whether we might end up with some transactions that are too big.

Please review to estimate how many interscore calls are made. It will certainly be an optimization to keep the addresses locally, but I am not sure it will be worth it. What would the savings be for a trader doing 500 routed 5-hop trades per hour if the addresses were held locally? That would be a somewhat extreme case, but not entirely out of the realm of possibility.

For the json_dumps calls we have just been constructing the json manually, which is pretty easy. json_loads is not so easy so we do use that api call. See here for an example constructing a DEX swap data string - https://github.com/balancednetwork/balanced-contracts/blob/development/core_contracts/loans/loans/loans.py#L683

for reference, you can see the step costs of different operations using the getStepCosts readonly method on the system SCORE, here - https://tracker.icon.foundation/contract/cx0000000000000000000000000000000000000001#readcontract
the cost of api calls is given as just one number, but that is only for the sha3_256 call. the others are multiples of that as given in the code, here - https://github.com/icon-project/icon-service/blob/master/iconservice/iconscore/icon_score_base2.py#L118
that's where you can see that json_dumps is 50000 step and json_loads is 40000.

**Comment by Skyvell** [comment]
Thanks for the feedback Dan, and the information about the different fees. I learned a lot actually. I've addressed the json_dumps concern you had. It was a bit more tricky when dealing with a list of addresses (createDataFieldRouter method), but it worked out :) I did some estimations on how getContractAddress interscore calls affect the overall fee. Hopefully I make myself understood.

### Fee estimation for using getContractAddress

**Router contract**:
- 0 calls to getContractAddress.

**Dex contract**:
- 1 call to getContractAddress per trade.

**Fee contract**:
Best case (transaction does not trigger conversion):
- 0 calls to getContractAddress.

Worst case (transaction does trigger conversion):
- 4 calls to getContractAddress (I can lower this to 3 so I'm using this number).

**Senario 1: Cost added by getContractAddress for a routed five hop trade without triggered conversion**:
5 * 25000 step (dex contract) = 125000 step = 0.00125 icx

**Senario 2: Cost added by getContractAddress for a routed five hop trade with triggered conversion**:
5 * 25000 step (dex contract) + 3 * 25000 step (fee contract) = 200000 step = 0.002 icx

Assuming a route is needed for the fee conversion there will be some extra hops needed to convert this fee. Assuming a route with 5 hops for this conversion we get an additional fee of 5 * 25000 step (dex contract) = 0.00125 icx, as a result of not having the fee_handler address locally in the dex contract.

**How often will senario 2 occur?**
To get a picture of how often senario 2 will occur, let the following be true:
- feeProcessingInterval is set to 1800 blocks, corresponsing to 60 minutes.
- There are 20 tokens listed on the DEX.

With these inital conditions, senario 2 will occur a maximum of 20 times in one hour no matter how many trades that occur. Assuming one particular trader only trades in 1 pool back and forth (e.g. baln -> bnusd, bnusd -> baln) that trader will at most trigger senario 2 two times during that hour, no matter how many trades he does.

**Conclusion**
Looking at the above information it seems that not having the fee_handler contract locally in the dex contract might be a bit inefficient, so it should probably be added there. Not having the addresses locally in the fee_handler contract will add an additional worst case cost of 75000 steps (0.00075 icx) to a transaction (only when fee conversion is triggered, which is pretty rare, depending on the settings of course). This case is a bit harder to judge. By retrieving the addresses via getContractAddress we get more compact and maintainable code, but the tradoff is a slightly higher transaction fee when conversions take place. Let me know what you think. Are you fine with this slightly higher occational transaction fee in order to get a bit more compact and maintainable code? Or would you prefer the slightly higher transaction fee efficiency?

**Review by dbrehmer — COMMENTED** [review]
Thanks for making the changes and step cost estimate. I'd agree that reading the addresses from governance will be worth a little additional cost for now.

A couple last things to consider - 
1. You mentioned the idea of the fee handler being incorporated into the DEX. I had not thought of that previously and it seems like it might be worth doing it that way. What are your thoughts on that option?
2. I had been thinking the conversion interval might be determined by a minimum accumulation of a given token, rather than a time interval. That seems like the more relevant number to trigger on since it will affect the markets. I don't think it will make too much difference, but we may want to tweak this a little at a later time. It should not be hard to change later if we want to try something else. What are your thoughts?

**Comment by Skyvell** [comment]
1. Sorry maybe I was not clear about what I meant, I said "incorporated", but what I meant was that currently the dex looks up the fee handler address via getContractAddress when it sends the fees for every trade and that was the inefficiency I was referring to. So I should probably add the fee handler contract address to the dex contract so it can be looked up locally.

2. I agree that this would be the more relevant number. I thought quite a bit about this when deciding on the approach to take. The issues I found with this approach is that we would be forced to set an individual threshold for each token, since it would not make sense to have the same token threshold for all tokens. For example if the threshold was 200 tokens, a threshold of 200 ethereum would not make sense, while it might make sense for ICX. Having individual thresholds would need to be "maintained" more. E.g. adjusting thresholds when tokens go up or down in value or adding a new threshold every time a token is added to the dex. A solution to this problem I though about was using a single threshold in bnusd and then pull prices from the liquidity pools or an oracle when checking to see if a token has accumulated enough value in the fee handler contract. But this introduces quite a bit of complexity in its own right.

**Comment by Skyvell** [comment]
Follow up question regarding (2): Is there an easy way to get the dollar value of a token listed on the dex via an interscore call to the dex? If this is easier than I thought then it might make sense to change from block time to usd threshold, either now, or to tweek that in the future.

**Review by dbrehmer — DISMISSED** [review]
Looks good.

It would not be a single call to the DEX to get the USD value. We are working on a proxy oracle that will give all prices for the tokens we work with. It will draw from the DEX and any other sources as needed. I think it makes sense to leave this for later optimization. Generally good not to optimize prematurely and only implement what really makes a difference.

We can get this on testnet and see how it works there.

**Review by simusud — COMMENTED** [review]
Looks good.

**Review by dbrehmer — APPROVED** [review]
Looks good.

**Comment by Skyvell** [comment]
@dbrehmer 
Sounds good.

**Pull request merged**
